apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /home/shaojieyue/.kube/config
leaderElection:
  leaderElect: true
  retryPeriod: 8s
  resourceName: my-custom-scheduler
  resourceNamespace: kube-system

profiles:
  - schedulerName: my-custom-scheduler
    plugins:
      filter:
        enabled:
          - name: HostNetwork